---
- name: "Play 1- cgi website configuration"
  hosts: localhost
  become: yes
  tasks:
    - name: "install apache"
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - httpd
          - vim
          - wget
          - tree
          - git
      tags:
        - install-repo

    - name: "Create a directory - doc root"
      file:
        path: /var/www/html/learnwithproject.com
        state: directory
        mode: '0755'
        owner: root
        group: root
      tags:
        - create-directory

    - name: "Configure Apache with docroot & Timeout 300 secs"
      copy:
        src: /etc/ansible/learnwithprojects.com/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: '0644'
      tags:
        - configure-apache

    - name: "code copy"
      git:
        repo: 'https://github.com/mailrahulsre/learnwithprojects.com.git'
        dest: /var/www/html/learnwithproject.com
        version: master
        force: yes
      tags: code-copy

    - name: "restart apache"
      service:
        name: httpd
        state: restarted
      tags: start-apache


